# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KevinBurdett.com
#email: kevin@kevinburdett.com
description: > # this means to ignore newlines until "baseurl:"
  Kevin's home on the internet, musings of a programmer adrift in Corporate America.
baseurl: ""
url: "http://kevinburdett.com" # the base hostname & protocol for your site
twitter_username: kevinburdett
github_username:  kburdett

# Build settings
markdown: kramdown
